//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaDominos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> ProDeID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> BaseID { get; set; }
        public Nullable<int> ToppingID { get; set; }
        public Nullable<int> RimID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
    
        public virtual Base Base { get; set; }
        public virtual Order Order { get; set; }
        public virtual ProDetail ProDetail { get; set; }
        public virtual Rim Rim { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
